default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payload-ws_development

test:
  <<: *default
  database: payload-ws_test

production:
  <<: *default
  database: payload-ws_production
  username: payload-ws
  password: <%= ENV['PAYLOAD-WS_DATABASE_PASSWORD'] %>
